version: "3.8"

services:
  # =======================
  # GATEWAY Laravel Service
  # =======================
  gateway:
    build:
      context: ./gateway
    container_name: gateway
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./gateway:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql_gateway
    command: php artisan serve --host=0.0.0.0 --port=8000

  # ============================
  # USER SERVICE Laravel Service
  # ============================
  user_service:
    build:
      context: ./user-service
    container_name: user_service
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - ./user-service:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql_user
    command: php artisan serve --host=0.0.0.0 --port=8000

  # ===============================
  # PRODUCT SERVICE Laravel Service
  # ===============================
  product_service:
    build:
      context: ./product-service
    container_name: product_service
    restart: unless-stopped
    ports:
      - "8002:8000"
    volumes:
      - ./product-service:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql_product
    command: php artisan serve --host=0.0.0.0 --port=8000

  # ==========
  # MySQLs
  # ==========
  mysql_gateway:
    image: mysql:8.0
    container_name: mysql_gateway
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gateway_db
      MYSQL_PASSWORD: root
    ports:
      - "33061:3306"
    volumes:
      - mysql_gateway_data:/var/lib/mysql

  mysql_user:
    image: mysql:8.0
    container_name: mysql_user
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_service_db
      MYSQL_PASSWORD: root
    ports:
      - "33062:3306"
    volumes:
      - mysql_user_data:/var/lib/mysql

  mysql_product:
    image: mysql:8.0
    container_name: mysql_product
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_service_db
      MYSQL_PASSWORD: root
    ports:
      - "33063:3306"
    volumes:
      - mysql_product_data:/var/lib/mysql

  # ==========
  # Redis
  # ==========
  redis:
    image: redis:7.0
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_gateway_data:
  mysql_user_data:
  mysql_product_data:
  redis_data:
